language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t vkrishna/docker-react .

script:
  - docker run -e CI=true vkrishna/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-053692227781"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
