sudo: required
services:
  - docker
before_install:
# testing before install
  - docker build -t krishna/client_react -f ./client/Dockerfile.dev ./client
#  currently we only haev react app to test
# so only build for react app
#  need to proceed in the same way for others as well
script:
 - docker run -e CI=true krishna/client_react npm run test
#  need to proceed in the same way for others

after_success:
#  once the test is successful we need to run build the prod version of the image 
  - docker build -t krishna/client-react ./client
  - docker build -t krishna/nginx-prod ./nginx
  - docker build -t krishna/server-node ./server
  - docker build -t krishna/worker-node ./worker

# once the docker build the prod version the images we need to push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push krishna/nginx-prod
