sudo: required
services:
  - docker

before-install:
  - docker build -t krishna123/docker-react -f Dockerfile.dev .
script:
  # - docker run krishna123/docker-react npm run test -- --coverage    
  - docker run krishna123/docker-react -e CI=true npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-053692227781"
  bucket_path: "docker-react"
  on:
    branch: dev_react
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


