version: "3.9"
services: 
  client-react:
    image: "vkrishna123/client-react:latest"
  
  server-node:
    image: "vkrishna123/server-node:latest"  
  
  worker-node:
    image: "vkrishna123/worker-node:latest"
  
  postgres:
    image: "postgres"

  redis:
    image: "redis"  

  nginx:
    image: "vkrishna123/nginx-prod:latest"
    restart: always
    ports: 
      - "80:80"  