version: "3.9"
services: 
  docker-react:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports: 
      - "3000:3000"
    restart: "always"  
    volumes: 
      - ./src:/docker-react-node-app/src
      - /docker-react-node-app/
  
  docker-react-test:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    restart: "unless-stopped"
    volumes: 
      - ./src/:/docker-react-node-app/src
      - /docker-react-node-app/
    command: ["npm", "test"]