version: "3"
services:
  fronend_react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
      - .:/frontend/

  fronend_react_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /frontend/node_modules
      - .:/frontend/
    command: ["npm", "test"]
