version: "3.9"
services: 
  client-react:
    image: "vkrishna123/client-react:latest"
  
  server-node:
    image: "vkrishna123/server-node:latest"  
    environment: 
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      
  worker-node:
    image: "vkrishna123/worker-node:latest"
    environment: 
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  postgres:
    image: "postgres:latest"
    environment: 
     POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  redis:
    image: "redis:latest"  

  nginx:
    image: "vkrishna123/nginx-prod:latest"
    restart: always
    ports: 
      - "80:80"  